"""
Django settings for mango_backend project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-24rua%c5hsaidmfb0zte77e8$$=v7+kbc2_c9b#8pug%&#y0=e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

AUTH_USER_MODEL = "users.User"

THEME_APPS = [
    # "modeltranslation",
    "jazzmin",
    "django_summernote",
]


INSTALLED_APPS = [
    *THEME_APPS,
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'manga',
    'common',
    'rest_framework',
    'phonenumber_field',
    'phonenumbers',
    'corsheaders',
    'django_filters',
    'drf_multiple_model',
    'rest_framework_simplejwt',

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mango_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mango_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "ru-RU"

TIME_ZONE = "Asia/Bishkek"

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files
STATIC_URL = "/back_static/"
STATIC_ROOT = os.path.join(BASE_DIR, "back_static")

# Media files
MEDIA_URL = "/back_media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "back_media")
X_FRAME_OPTIONS = "SAMEORIGIN"

EXTRA_SMALL_THUMBNAIL_SIZE = 100, 100
SMALL_THUMBNAIL_SIZE = 512, 512
MEDIUM_THUMBNAIL_SIZE = 1024, 1024
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "DATE_INPUT_FORMATS": ["%d.%m.%Y"],
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
}


# JAZZMIN_SETTINGS = {
#     "site_title": "Manga TT for Geeks",
#     "site_header": "Манга",
#     "site_logo_classes": "img-circle",
#     "site_icon": '/assets/icons/admin_logo.svg',
#     "welcome_sign": "Добро пожаловать в панель администратора сайта Манга!",
#     "copyright": "GeekStudio(Usmanov Kanat)",
#     "search_model": "auth.User",
#     "user_avatar": 'None',
#     "topmenu_links": [
#         {"name": "Главная", "url": "admin:index", "permissions": ["auth.view_user"]},
#     ],
#     "usermenu_links": [
#         {
#             "model": "auth.user",
#         },
#     ],
#     "order_with_respect_to": [
#         # apps
#         "informations",
#         "announcements",
#         "decree",
#         "vote",
#         "auth",
#     ],
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "language_chooser": True,
#     "hide_apps": [],
#     "hide_models": [],
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#         "blog": "fas fa-book",
#     },
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-thumbtack",
#     "related_modal_active": True,
#     "custom_css": "/common/style.css",
#     "custom_js": None,
#     "show_ui_builder": False,
#     "changeform_format": "horizontal_tabs",
#     "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
#     "icons": {
#         "announcements.Vacancy": "fas fa-clipboard-check",
#         "announcements.Conferences": "fas fa-folder",
#         "announcements.UsefulInformation": "fas fa-newspaper",

#         "decree.RegionalCity": "fa fa-location-arrow",
#         "decree.Region": "fa fa-location-arrow",
#         "decree.District": "fa fa-location-arrow",
#         "decree.RuralManagement": "fas fa-map-pin",
#         "decree.Resolutions": "fas fa-file-alt",

#         "informations.CategoryOfQuestions": "fa fa-sort",
#         "informations.Question": "fas fa-question",
#         "informations.EmployeeCard": "fas fa-users",
#         "informations.Act": "fas fa-gavel",
#         "informations.ImageModel": "fas fa-image",
#         "informations.News": "fa fa-newspaper",
#         "informations.TestsCategory": "fas fa-list-ol",
#         "informations.Tests": "fas fa-list-ol",

#         "vote.CityDepartment": "fa fa-location-arrow",
#         "vote.Region": "fa fa-location-arrow",
#         "vote.District": "fa fa-location-arrow",
#         "vote.RuralManagement": "fas fa-map-pin",
#         "vote.Vote": "fas fa-vote-yea",
#         "vote.Answer": "fas fa-list-alt",
#         "vote.UserVoting": "fas fa-user-check",
#     },
# }

# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,
#     "brand_colour": "navbar-dark",
#     "accent": "accent-primary",
#     "navbar": "navbar-light",
#     "no_navbar_border": False,
#     "navbar_fixed": True,
#     "layout_boxed": False,
#     "footer_fixed": False,
#     "sidebar_fixed": True,
#     "sidebar": "sidebar-dark-warning",
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": False,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_legacy_style": True,
#     "sidebar_nav_flat_style": False,
#     "theme": "lumen",
#     "dark_mode_theme": None,
#     "button_classes": {
#         "primary": "btn-outline-primary",
#         "secondary": "btn-outline-secondary",
#         "info": "btn-outline-info",
#         "warning": "btn-outline-warning",
#         "danger": "btn-outline-danger",
#         "success": "btn-outline-success"
#     },
#     "actions_sticky_top": True
# }